export const GET_SEATS = "GET_SEATS";
export const SUBMIT_FORM = "SUBMIT_FORM";
export const SET_PLACES_TO_RESERVATION = "SET_PLACES_TO_RESERVATION";
export const NORMALIZED_HALL_SCHEME = "NORMALIZED_HALL_SCHEME";
export const ADD_PLACE_TO_RESERVATION = "ADD_PLACE_TO_RESERVATION";
export const DELETE_PLACE_FROM_RESERVATION = "DELETE_PLACE_FROM_RESERVATION";
export const IS_HALL_FULL = "IS_HALL_FULL";
export const ARE_THERE_ENOUGH_PLACES = "ARE_THERE_ENOUGH_PLACES";
